version: '3.4'

services:
  mysqlpismo8:
    image: mysql:8
    container_name: mysqlpismo8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pismo

  spring-pismo:
    depends_on:
      - "mysqlpismo8"
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: spring-pismo
    volumes:
      - "./target/pismo-0.0.1-SNAPSHOT.jar:/app.jar"
    ports:
      - 8761:8761
