spring:
  application:
    name: pismo
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysqlpismo8:3306/pismo
    username: root
    password: root
server:
  port: 8761